// seed/data.js

const products = [
  // ============================
  // WOMEN — product_1 to product_12
  // ============================
  {
    name: "Mauve Bell Sleeve Top",
    image: "product_1.png",
    category: "women",
    new_price: 799,
    old_price: 999,
    available: true,
  },
  {
    name: "Pastel Pink Ruffled Blouse",
    image: "product_2.png",
    category: "women",
    new_price: 749,
    old_price: 899,
    available: true,
  },
  {
    name: "Floral Print Chiffon Top",
    image: "product_3.png",
    category: "women",
    new_price: 699,
    old_price: 899,
    available: true,
  },
  {
    name: "White Lace Peplum Top",
    image: "product_4.png",
    category: "women",
    new_price: 850,
    old_price: 1100,
    available: true,
  },
  {
    name: "Black Slim Fit Crop Top",
    image: "product_5.png",
    category: "women",
    new_price: 650,
    old_price: 800,
    available: true,
  },
  {
    name: "Olive Green Casual Tunic",
    image: "product_6.png",
    category: "women",
    new_price: 720,
    old_price: 880,
    available: true,
  },
  {
    name: "Sky Blue V-Neck Blouse",
    image: "product_7.png",
    category: "women",
    new_price: 799,
    old_price: 950,
    available: true,
  },
  {
    name: "Beige Pleated Full-Sleeve Top",
    image: "product_8.png",
    category: "women",
    new_price: 820,
    old_price: 1000,
    available: true,
  },
  {
    name: "Rust Orange Wrap Top",
    image: "product_9.png",
    category: "women",
    new_price: 780,
    old_price: 950,
    available: true,
  },
  {
    name: "Classic Black Button-Down Shirt",
    image: "product_10.png",
    category: "women",
    new_price: 870,
    old_price: 1100,
    available: true,
  },
  {
    name: "Lilac Oversized Casual Tee",
    image: "product_11.png",
    category: "women",
    new_price: 650,
    old_price: 799,
    available: true,
  },
  {
    name: "Embroidered Boho White Top",
    image: "product_12.png",
    category: "women",
    new_price: 900,
    old_price: 1200,
    available: true,
  },

  // ============================
  // MEN — product_13 to product_24
  // ============================
  {
    name: "Navy Blue Denim Jacket",
    image: "product_13.png",
    category: "men",
    new_price: 1499,
    old_price: 1999,
    available: true,
  },
  {
    name: "Classic Plaid Check Shirt",
    image: "product_14.png",
    category: "men",
    new_price: 950,
    old_price: 1300,
    available: true,
  },
  {
    name: "Olive Green Bomber Jacket",
    image: "product_15.png",
    category: "men",
    new_price: 1800,
    old_price: 2400,
    available: true,
  },
  {
    name: "Grey Cotton Casual Shirt",
    image: "product_16.png",
    category: "men",
    new_price: 850,
    old_price: 1100,
    available: true,
  },
  {
    name: "Black Hooded Jacket",
    image: "product_17.png",
    category: "men",
    new_price: 1599,
    old_price: 2000,
    available: true,
  },
  {
    name: "Maroon Slim Fit Shirt",
    image: "product_18.png",
    category: "men",
    new_price: 880,
    old_price: 1200,
    available: true,
  },
  {
    name: "Khaki Utility Jacket",
    image: "product_19.png",
    category: "men",
    new_price: 1700,
    old_price: 2200,
    available: true,
  },
  {
    name: "White Linen Shirt",
    image: "product_20.png",
    category: "men",
    new_price: 1100,
    old_price: 1400,
    available: true,
  },
  {
    name: "Steel Grey Sports Jacket",
    image: "product_21.png",
    category: "men",
    new_price: 1600,
    old_price: 2100,
    available: true,
  },
  {
    name: "Teal Printed Casual Shirt",
    image: "product_22.png",
    category: "men",
    new_price: 900,
    old_price: 1200,
    available: true,
  },
  {
    name: "Camel Brown Overcoat",
    image: "product_23.png",
    category: "men",
    new_price: 1999,
    old_price: 2600,
    available: true,
  },
  {
    name: "Black Formal Slim Shirt",
    image: "product_24.png",
    category: "men",
    new_price: 999,
    old_price: 1300,
    available: true,
  },

  // ============================
  // KIDS — product_25 to product_36
  // ============================
  {
    name: "Kids Yellow Cartoon Hoodie",
    image: "product_25.png",
    category: "kids",
    new_price: 550,
    old_price: 700,
    available: true,
  },
  {
    name: "Blue Denim Dungaree Set",
    image: "product_26.png",
    category: "kids",
    new_price: 650,
    old_price: 850,
    available: true,
  },
  {
    name: "Unicorn Printed Pink Top",
    image: "product_27.png",
    category: "kids",
    new_price: 520,
    old_price: 700,
    available: true,
  },
  {
    name: "Kids Green Winter Jacket",
    image: "product_28.png",
    category: "kids",
    new_price: 750,
    old_price: 950,
    available: true,
  },
  {
    name: "Navy Organic Cotton Tee",
    image: "product_29.png",
    category: "kids",
    new_price: 450,
    old_price: 600,
    available: true,
  },
  {
    name: "Striped Red Full Sleeves Shirt",
    image: "product_30.png",
    category: "kids",
    new_price: 499,
    old_price: 650,
    available: true,
  },
  {
    name: "Kids Purple Fleece Jacket",
    image: "product_31.png",
    category: "kids",
    new_price: 680,
    old_price: 900,
    available: true,
  },
  {
    name: "Girls Floral Summer Dress",
    image: "product_32.png",
    category: "kids",
    new_price: 620,
    old_price: 800,
    available: true,
  },
  {
    name: "Boys Printed Cotton Shirt",
    image: "product_33.png",
    category: "kids",
    new_price: 540,
    old_price: 700,
    available: true,
  },
  {
    name: "Kids Grey Hoodie",
    image: "product_34.png",
    category: "kids",
    new_price: 500,
    old_price: 650,
    available: true,
  },
  {
    name: "Girls Pink Layered Top",
    image: "product_35.png",
    category: "kids",
    new_price: 560,
    old_price: 720,
    available: true,
  },
  {
    name: "Kids Tangerine Pop Tee",
    image: "product_36.png",
    category: "kids",
    new_price: 450,
    old_price: 580,
    available: true,
  },
];

module.exports = products;
